### ISSUE TITLE
hubot-tell script doesn't seem to work

### ISSUE THREAD

**Issue by jmatsushita** [RocketChat/hubot-rocketchat#102]
Adding it to the EXTERNAL_SCRIPTS and using ```hubot tell username something``` doesn't seem to work.

**Comment by geekgonecrazy** [comment]
I believe this is dependant on the robot.enter.  This event is currently not supported.  

In rocket.chat traditionally someone does not leave and enter a room like they would with IRC.  They are usually still in the room, and just simply login again and their presence is set to available.

**Comment by jmatsushita** [comment]
Seems that interpreting robot.enter as presence being available in that
room would work. Unless you can think of a case where it would break things
(more than not implementing it)?

**Comment by Sing-Li** [comment]
Enter  is *fully* implemented quite a while ago !

https://github.com/RocketChat/hubot-rocketchat/issues/68

IRC was invented back in the days of "simple presence", and Rocket.Chat lives in a world of "voodoo presence" - chances of having IRC-era enter/leave bots working is close to zero.

**Comment by jmatsushita** [comment]
So then the hubot-tell big is because of something else? Let me know if
there's more troubleshooting I can do.

**Comment by geekgonecrazy** [comment]
@jmatsushita if you have use hubot-tell to tell someone when they come back.  Then simply have the person leave the channel and re-join.  The bot should see it and send them a message.

So technically the script is working as expected.

But since we don't usually leave and join channels.  IRC style scripts like that really aren't useful in rocket.chat.

Really since that person is technically already there all you need to do is:
```
@user: message
```

And they will see it when they log in again.  So having the bot tell them really isn't needed :)

**Comment by jmatsushita** [comment]
> So technically the script is working as expected.

Err... that's an interesting way to put it. Your workaround is also interesting.

But hubot-tell then indeed doesn't "functionally" work with hubot-rocketchat now as expected.

**Comment by geekgonecrazy** [comment]
@jmatsushita this isn't really a work around.  That script is simply designed to work based on enter and leave. So at this point in time it works exactly as expected.  If you leave the room and re-enter it'll alert you.

I think we will add ability for the bot to subscribe to presence of users... But its going to be up to the scripts like hubot-tell to modify to look at presence instead of enter / leave.

Presence is not entering / leaving a channel. Its much more complicated then the IRC status's of connected or disconnected that this script needs.

I'm going to go ahead and close this. Because like we said, this works exactly as the script is designed to.

**Comment by geekgonecrazy** [comment]
I have created another issue to address the presence subscription: #106

**Comment by jmatsushita** [comment]
Ok thanks for spending the time explaining in more detail. I do get it now! Cheers! Jun.
