### ISSUE TITLE
Getting started, does this repo's sample script not work or have I gone wrong? [logs attached]

### ISSUE THREAD

**Issue by Jack-Collins** [RocketChat/hubot-rocketchat#124]
![image](https://cloud.githubusercontent.com/assets/13108027/15672510/f34e8d30-2728-11e6-9c92-2d7ad2eb3be0.png)

**Comment by Jack-Collins** [comment]
also there is no hubot-scripts.json in this repo?

**Comment by timkinnane** [comment]
hubot-scripts.json is depreciated. Hubot used to include a bunch of scripts within the main repo, but now they're all loaded from individual npm packages and included in a bot using through 'external-scripts.json'. The file can be removed, probably just a remnant from an out of date generator.

As for the bot not responding to you, I'm having the same problem. Bots can **hear** but they don't **respond**, this seems to be since last version but rolling back didn't help me, could be a dependency issue. Will come back if I find a solution.

**Comment by timkinnane** [comment]
I found my problem, maybe same as yours. Bot responds only to its name from the package.json. Doesn't work with names set in environment configs, like BOT_NAME or ROCKETCHAT_USER. I think the adapter needs to be updated to accept those variables as aliases for itself.

**Comment by geekgonecrazy** [comment]
@timkinnane merged your pull request should now be available in the latest version of the adapter 👍

**Comment by timkinnane** [comment]
👍 Thanks! My first PR ❤️
