### ISSUE TITLE
Error download asteroid

### ISSUE THREAD

**Issue by viniciuscr** [RocketChat/hubot-rocketchat#188]
hey guys.
It isn´t a real bug but it causes me lots of trouble.
the asteroid dependency is set like this:
"asteroid": "https://github.com/RocketChat/asteroid.git"

Maybe because I am behind a firewall that switches certificates and all NPM can´t download it.
I have reconfigured my git with proxy plus certificates and it works nicely on the command line, but for some reason the npm is giving me an error 

` Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
...
 git+https://github.com/RocketChat/asteroid.git resetting remote C:\Users ....
`

I have tried clone hubot-rocketchat and changed the dependency to   `"asteroid" : "^2.0.3"` but when I launch the bot it gives me a error that asteroid is not a function.

So my question is: Could you guys change it to stop trying download asteroid from git and use the npm version?

**Comment by geekgonecrazy** [comment]
@viniciuscr we can give it a try.  We had to initially because we were making some changes that weren't upstream.  We can revisit this.

**Comment by danielo515** [comment]
This is inconvenient in many many ways. One of them is that I can't use a slim version of node docker image just because this package requires git. The difference in size is quite noticeable for something that will be much more easier to manage with just npm itself. I don't see the advantage

**Comment by jszaszvari** [comment]
@danielo515 why not? There's nothing stopping you from just installing git into the node-slim image at build time, then remove it when done

**Comment by danielo515** [comment]
@jszaszvari that is an extra step that not only adds to build time ,but also to final size. Even if you remove got it will leave some extra MB. I don't see the advantages of adding extra build steps and other problems when we have an excellent package manager at our disposal

**Comment by jszaszvari** [comment]
I disagree. There's plenty of ways to install and remove a package without using a single KB more of apace.

Somewhere down the line you will run into more external dependencies, it's bound to happen with a project as large as this. 

node-slim isn't recommended for runtime if you have any external dependencies at all. 

Its really not the end of the world if the image your using goes from 120mb to 120mb because you need to install something. Also the build time is only increased for that initial build of the image, by what, 15 seconds?
