### ISSUE TITLE
Bot unable to listen to its own messages

### ISSUE THREAD

**Issue by vsinha** [RocketChat/hubot-rocketchat#249]
Haven't found anything in the docs or other issues for this-- is it possible for the hubot rc adapter to relay back messages emitted by itself?

**Comment by geekgonecrazy** [comment]
There is code explicitly put in place to prevent this. What's the use case here?

**Comment by epaaj** [comment]
I stumbled onto this issue too after writing a few scripts for Hubot. I schedule the bot to post a poll with the command `!poll "Question" "Answer 1" "Answer 2"`. I also have it scan for these commands and count the number of answers, store that and when the poll is posted it adds the reactions from 1-9 so that the users won't have to search for them and also makes them appear in order.

This works fine as long as it's a user who posts the poll command. But when Hubot posts the sceduled command it won't work as it cannot trigger on its own messages and count the number of answers.

Also I'm having trouble getting the message id for messages sent by the bot. Listening for keywords could be a solution to get the message id and doing whatever you want with it. Not perfect but one way of doing it.
