### ISSUE TITLE
Multiple Hubot in single LiveChat

### ISSUE THREAD

**Issue by hojat-kaveh** [RocketChat/hubot-rocketchat#277]
Is it possible to have multiple instance of Hubot in a **single**  LiveChat?

**Comment by timkinnane** [comment]
Hi @hojat-kaveh - I am the current maintainer of this repo but I'm not too familiar with livechat features and user management. I can only resolve issues to do with the adapter supporting the livechat message stream, which it does as long as the `RESPOND_TO_LIVECHAT` environment variable is set. For that you could also read this issue #195 which was resolved and might give you some context.

I've added an issue [on the docs repo](https://github.com/RocketChat/docs/issues/779) to try and get some clarity around this for livechat users. So please comment there to follow up. I'll close this one because there's not much resolution I can offer beyond that. You should also try the other avenues of support listed here: https://rocket.chat/support
